In [2]:
import pandas as pd

df = pd.read_csv('../data/raw/public_apis_raw.csv')
df.shape

(1737, 7)

In [3]:
df.isnull().sum()

name           0
description    0
category       0
auth           0
https          0
cors           0
link           0
dtype: int64

In [4]:
df.describe()

,name,description,category,auth,https,cors,link
count,1737,1737,1737,1737,1737,1737,1737
unique,1716,1683,51,7,2,3,1734
top,Cat Facts,Music,Development,No,Yes,Unknown,https://isitdownstatus.com
freq,2,9,157,817,1645,986,2

In [5]:
duplicates = df[df.duplicated(subset='name', keep=False)].sort_values('name')
duplicates.shape

(42, 7)

In [6]:
duplicates[['name', 'description', 'category', 'link']]

,name,description,category,link
109,Bhagavad Gita,Open Source Shrimad Bhagavad Gita API includin...,Books,https://docs.bhagavadgitaapi.in
110,Bhagavad Gita,Bhagavad Gita text,Books,https://bhagavadgita.io/api
2,Cat Facts,Daily cat facts,Animals,https://alexwohlbruck.github.io/cat-facts/
3,Cat Facts,Random cat facts,Animals,https://catfact.ninja/
528,Cloudmersive Validate,"Validate email addresses, phone numbers, VAT n...",Email,https://cloudmersive.com/validate-api
1235,Cloudmersive Validate,Validate international phone numbers,Phone,https://cloudmersive.com/phone-number-validati...
991,Covid-19,"Covid 19 spread, infection and recovery",Health,https://covid19api.com/
992,Covid-19,"Covid 19 cases, deaths and recovery per country",Health,https://github.com/M-Media-Group/Covid-19-API
6,Dog Facts,Random dog facts,Animals,https://dukengn.github.io/Dog-facts-API/
7,Dog Facts,Random facts of Dogs,Animals,https://kinduff.github.io/dog-api/
100,Helium,"Helium is a global, distributed network of Hot...",Blockchain,https://docs.helium.com/api/blockchain/introdu...
619,Helium,"News with media bias scoring, balanced news sy...",Finance,https://heliumtrades.com/mcp-page/
397,JSONPlaceholder,Fake REST API for testing and prototyping,Development,https://jsonplaceholder.typicode.com
1491,JSONPlaceholder,Fake data for testing and prototyping,Test Data,http://jsonplaceholder.typicode.com/
556,JokeAPI,Programmable jokes in multiple languages with ...,Entertainment,https://v2.jokeapi.dev/
736,JokeAPI,"Programming, Miscellaneous and Dark Jokes",Games & Comics,https://sv443.net/jokeapi/v2/
849,Mapbox,Create/customize beautiful digital maps,Geocoding,https://docs.mapbox.com/
1531,Mapbox,"Maps, directions, geocoding",Tracking,https://docs.mapbox.com/api/
176,Non-Working Days,Database of ICS files for non working days,Calendar,https://github.com/gadael/icsdb
177,Non-Working Days,"Simple REST API for checking working, non-work...",Calendar,https://isdayoff.ru
1295,Numbers,"Number of the day, random number, number facts...",Science & Math,https://math.tools/api/numbers/
1296,Numbers,Facts about numbers,Science & Math,http://numbersapi.com
950,"Open Government, Mexico",Mexican Statistical Government Open Data,Government,https://www.inegi.org.mx/datos/
951,"Open Government, Mexico",Mexico Government Open Data,Government,https://datos.gob.mx/
578,Open-Meteo,Free weather API for non-commercial use,Environment,https://open-meteo.com/
1717,Open-Meteo,Global weather forecast API for non-commercial...,Weather,https://open-meteo.com/
431,QR code,Create an easy to read QR code and URL shortener,Development,https://www.qrtag.net/api/
432,QR code,Generate and decode / read QR code graphics,Development,http://goqr.me/api/
1681,SWAPI,All the Star Wars data you've ever wanted,Video,https://swapi.dev/
1682,SWAPI,All things Star Wars,Video,https://www.swapi.tech
1305,SpaceX,"Company, vehicle, launchpad and launch data",Science & Math,https://github.com/r-spacex/SpaceX-API
1306,SpaceX,"GraphQL, Company, Ships, launchpad and launch ...",Science & Math,https://api.spacex.land/graphql/
771,Steam,Steam Web API documentation,Games & Comics,https://steamapi.xpaw.me/
772,Steam,Internal Steam Web API documentation,Games & Comics,https://github.com/Revadike/InternalSteamWebAP...
563,TasteDive,"Content-based recommendations for movies, musi...",Entertainment,https://tastedive.com/read/api
1114,TasteDive,Similar artist API (also works for movies and ...,Music,https://tastedive.com/read/api
1606,Transport for Switzerland,Official Swiss Public Transport Open Data,Transportation,https://opentransportdata.swiss/en/
1607,Transport for Switzerland,Swiss public transport API,Transportation,https://transport.opendata.ch/
1608,Transport for The Netherlands,"NS, only trains",Transportation,http://www.ns.nl/reisinformatie/ns-api
1609,Transport for The Netherlands,"OVAPI, country-wide public transport",Transportation,https://github.com/skywave/KV78Turbo-OVAPI/wiki
57,URLhaus,Bulk queries and Download Malware Samples,Anti-Malware,https://urlhaus-api.abuse.ch/
1360,URLhaus,Database of malicious URLs used for malware di...,Security,https://urlhaus.abuse.ch/api/

In [7]:
df["https"].value_counts(dropna=False)

https
Yes    1645
No       92
Name: count, dtype: int64

In [8]:
df["https"] = df["https"].map({
    "Yes": True,
    "No": False
})

In [9]:
print(df["https"].value_counts())
print(df["https"].dtype)

https
True     1645
False      92
Name: count, dtype: int64
bool

In [10]:
df['https'].head(10)

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
8    True
9    True
Name: https, dtype: bool

In [11]:
df['cors'] = df['cors'].map({'Yes': True, 'No': False, 'Unknown': None})

In [12]:
df['cors'].value_counts(dropna=False)

cors
None     986
True     594
False    157
Name: count, dtype: int64

In [13]:
df.dtypes

name              str
description       str
category          str
auth              str
https            bool
cors           object
link              str
dtype: object

In [14]:
df['auth'] = df['auth'].str.replace('`', '', regex=False).str.strip()

In [15]:
df['auth'].value_counts()

auth
No               819
apiKey           761
OAuth            150
X-Mashape-Key      6
User-Agent         1
Name: count, dtype: int64

In [16]:
df.dtypes

name              str
description       str
category          str
auth              str
https            bool
cors           object
link              str
dtype: object

In [17]:
df['auth'].value_counts()

auth
No               819
apiKey           761
OAuth            150
X-Mashape-Key      6
User-Agent         1
Name: count, dtype: int64

In [18]:
df.to_csv('../data/processed/public_apis_processed.csv', index=False)           
print(f"saved {len(df)}clean rows")

saved 1737clean rows

In [19]:
df['category'].value_counts()

category
Development                       157
Government                        104
Games & Comics                    103
Geocoding                          95
Transportation                     80
Cryptocurrency                     79
Finance                            67
Open Data                          54
Social                             51
Sports & Fitness                   48
Video                              48
Security                           47
Science & Math                     40
Health                             39
Weather                            39
Documents & Productivity           38
Machine Learning                   35
Music                              35
Business                           32
Photography                        31
Test Data                          30
Animals                            26
Food & Drink                       26
Books                              25
Personality                        25
Art & Design                       24
Email                              24
Jobs                               23
News                               23
Currency Exchange                  22
Environment                        22
URL Shorteners                     20
Anime                              19
Text Analysis                      19
Calendar                           18
Cloud Storage & File Sharing       18
Shopping                           18
Entertainment                      17
Anti-Malware                       16
Blockchain                         15
Dictionaries                       13
Tracking                           11
Data Validation                    10
Vehicle                            10
Open Source Projects                9
Authentication & Authorization      7
Phone                               7
Continuous Integration              6
Programming                         5
Patent                              4
Events                              3
Name: count, dtype: int64

In [20]:
df['auth'].value_counts()

auth
No               819
apiKey           761
OAuth            150
X-Mashape-Key      6
User-Agent         1
Name: count, dtype: int64

In [21]:
pd.crosstab(df['category'], df['auth'])

auth                            No  OAuth  User-Agent  X-Mashape-Key  apiKey
category
Animals                         20      0           0              0       6
Anime                           10      5           0              0       4
Anti-Malware                     2      0           0              0      14
Art & Design                    12      2           0              0      10
Authentication & Authorization   0      0           0              0       7
Blockchain                       8      0           0              0       7
Books                           18      3           0              0       4
Business                        10      6           0              0      16
Calendar                        12      1           0              0       5
Cloud Storage & File Sharing     4      4           0              0      10
Continuous Integration           0      1           0              0       5
Cryptocurrency                  32      0           0              0      47
Currency Exchange               12      0           0              0      10
Data Validation                  2      0           0              0       8
Development                     70     14           0              1      72
Dictionaries                     5      0           0              0       8
Documents & Productivity         3      8           0              0      27
Email                            9      0           0              0      15
Entertainment                   15      0           0              0       2
Environment                     12      0           0              0      10
Events                           0      1           0              0       2
Finance                         15      5           0              0      47
Food & Drink                    11      1           0              0      14
Games & Comics                  69      6           0              2      26
Geocoding                       47      1           0              0      47
Government                      78      4           0              0      22
Health                          29      1           0              0       9
Jobs                             8      2           0              0      13
Machine Learning                 8      1           0              0      26
Music                           11     11           0              0      13
News                             7      2           0              0      14
Open Data                       33      4           0              0      17
Open Source Projects             8      1           0              0       0
Patent                           2      1           0              0       1
Personality                     20      1           0              0       4
Phone                            1      0           0              0       6
Photography                      6      8           0              0      17
Programming                      1      0           0              0       4
Science & Math                  33      1           0              0       6
Security                        18      1           0              0      28
Shopping                         1      6           0              0      11
Social                           9     25           0              0      17
Sports & Fitness                21      3           0              2      22
Test Data                       25      0           0              0       5
Text Analysis                    1      5           0              0      13
Tracking                         3      0           0              1       7
Transportation                  39      9           0              0      32
URL Shorteners                  10      1           0              0       9
Vehicle                          4      1           0              0       5
Video                           28      3           0              0      17
Weather                         17      1           1              0      20

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
df['category'].value_counts().tail(10)

category
Tracking                          11
Data Validation                   10
Vehicle                           10
Open Source Projects               9
Authentication & Authorization     7
Phone                              7
Continuous Integration             6
Programming                        5
Patent                             4
Events                             3
Name: count, dtype: int64

In [24]:
df['category'].value_counts().sort_values()

category
Events                              3
Patent                              4
Programming                         5
Continuous Integration              6
Authentication & Authorization      7
Phone                               7
Open Source Projects                9
Vehicle                            10
Data Validation                    10
Tracking                           11
Dictionaries                       13
Blockchain                         15
Anti-Malware                       16
Entertainment                      17
Cloud Storage & File Sharing       18
Shopping                           18
Calendar                           18
Text Analysis                      19
Anime                              19
URL Shorteners                     20
Environment                        22
Currency Exchange                  22
News                               23
Jobs                               23
Email                              24
Art & Design                       24
Personality                        25
Books                              25
Food & Drink                       26
Animals                            26
Test Data                          30
Photography                        31
Business                           32
Machine Learning                   35
Music                              35
Documents & Productivity           38
Health                             39
Weather                            39
Science & Math                     40
Security                           47
Sports & Fitness                   48
Video                              48
Social                             51
Open Data                          54
Finance                            67
Cryptocurrency                     79
Transportation                     80
Geocoding                          95
Games & Comics                    103
Government                        104
Development                       157
Name: count, dtype: int64

In [25]:
# this is the code we have that if the value of any category is less than 15 add in other solve class imbalance problem.
category_counts = df['category'].value_counts()
small_categories = category_counts[category_counts < 15].index
df['category'] = df['category'].where(~df['category'].isin(small_categories), 'Other')

df['category'].value_counts()

category
Development                     157
Government                      104
Games & Comics                  103
Geocoding                        95
Other                            85
Transportation                   80
Cryptocurrency                   79
Finance                          67
Open Data                        54
Social                           51
Sports & Fitness                 48
Video                            48
Security                         47
Science & Math                   40
Health                           39
Weather                          39
Documents & Productivity         38
Machine Learning                 35
Music                            35
Business                         32
Photography                      31
Test Data                        30
Animals                          26
Food & Drink                     26
Books                            25
Personality                      25
Art & Design                     24
Email                            24
Jobs                             23
News                             23
Currency Exchange                22
Environment                      22
URL Shorteners                   20
Anime                            19
Text Analysis                    19
Calendar                         18
Cloud Storage & File Sharing     18
Shopping                         18
Entertainment                    17
Anti-Malware                     16
Blockchain                       15
Name: count, dtype: int64

In [26]:
df['category'].nunique()

41

In [27]:
from sklearn.model_selection import train_test_split

train_df, temp_df = train_test_split(
    df, test_size=0.3, stratify=df['category'], random_state=42
)#100 test - 30 then test_size = 30 % and 70 is train size
val_df, test_df = train_test_split(
    temp_df, test_size=0.5, stratify=temp_df['category'], random_state=42
)# split test data intp 50-50  
print(train_df.shape, val_df.shape, test_df.shape)

(1215, 7) (261, 7) (261, 7)

1,737 total
=Train      ≈ 1,216 (70%)
,Validation ≈ 260  (15%)

, Test       ≈ 261  (15%)

In [28]:
train_df.to_csv('../data/processed/train.csv', index=False)
val_df.to_csv('../data/processed/val.csv', index=False)
test_df.to_csv('../data/processed/test.csv', index=False)

print("Saved all")

Saved all

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=2000, stop_words='english')

X_train = vectorizer.fit_transform(train_df['description'])
X_val = vectorizer.transform(val_df['description'])
X_test = vectorizer.transform(test_df['description'])

print(X_train.shape, X_val.shape, X_test.shape)

(1215, 2000) (261, 2000) (261, 2000)

In [30]:
import joblib

joblib.dump(vectorizer, '../artifacts/tfidf_vectorizer.pkl')
print("Vectorizer saved")

Vectorizer saved

In [31]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000, random_state=42)
model.fit(X_train, train_df['category'])

print("Model trained")

Model trained

In [32]:
from sklearn.metrics import accuracy_score, classification_report

val_predictions = model.predict(X_val)
accuracy = accuracy_score(val_df['category'], val_predictions)

print(f"Validation accuracy: {accuracy:.2%}")

Validation accuracy: 42.53%

In [33]:
print(classification_report(val_df['category'], val_predictions))

                              precision    recall  f1-score   support

                     Animals       0.75      0.75      0.75         4
                       Anime       1.00      0.67      0.80         3
                Anti-Malware       0.00      0.00      0.00         3
                Art & Design       0.00      0.00      0.00         4
                  Blockchain       0.00      0.00      0.00         2
                       Books       0.00      0.00      0.00         3
                    Business       1.00      0.40      0.57         5
                    Calendar       0.00      0.00      0.00         3
Cloud Storage & File Sharing       0.00      0.00      0.00         3
              Cryptocurrency       0.75      0.75      0.75        12
           Currency Exchange       1.00      0.50      0.67         4
                 Development       0.17      0.91      0.29        23
    Documents & Productivity       1.00      0.40      0.57         5
                       Email       0.67      0.50      0.57         4
               Entertainment       0.00      0.00      0.00         2
                 Environment       0.00      0.00      0.00         3
                     Finance       0.50      0.30      0.38        10
                Food & Drink       0.00      0.00      0.00         4
              Games & Comics       0.43      0.56      0.49        16
                   Geocoding       0.70      0.50      0.58        14
                  Government       0.38      0.50      0.43        16
                      Health       0.00      0.00      0.00         6
                        Jobs       1.00      1.00      1.00         3
            Machine Learning       1.00      0.17      0.29         6
                       Music       1.00      0.80      0.89         5
                        News       1.00      0.50      0.67         4
                   Open Data       0.00      0.00      0.00         8
                       Other       0.70      0.54      0.61        13
                 Personality       1.00      0.25      0.40         4
                 Photography       0.00      0.00      0.00         4
              Science & Math       0.00      0.00      0.00         6
                    Security       1.00      0.14      0.25         7
                    Shopping       0.00      0.00      0.00         2
                      Social       1.00      0.38      0.55         8
            Sports & Fitness       0.60      0.43      0.50         7
                   Test Data       0.75      0.75      0.75         4
               Text Analysis       0.67      0.67      0.67         3
              Transportation       0.57      0.33      0.42        12
              URL Shorteners       1.00      0.33      0.50         3
                       Video       1.00      0.14      0.25         7
                     Weather       0.83      0.83      0.83         6

                    accuracy                           0.43       261
                   macro avg       0.52      0.34      0.38       261
                weighted avg       0.54      0.43      0.41       261

c:\Users\Hii\Code\ai-api-intelligence\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Hii\Code\ai-api-intelligence\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Hii\Code\ai-api-intelligence\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [34]:
model_balanced = LogisticRegression(max_iter=1000, random_state=42, class_weight='balanced')
model_balanced.fit(X_train, train_df['category'])

val_predictions_balanced = model_balanced.predict(X_val)
accuracy_balanced = accuracy_score(val_df['category'], val_predictions_balanced)

print(f"Validation accuracy (balanced): {accuracy_balanced:.2%}")
print(classification_report(val_df['category'], val_predictions_balanced))

Validation accuracy (balanced): 48.28%
                              precision    recall  f1-score   support

                     Animals       0.57      1.00      0.73         4
                       Anime       1.00      0.67      0.80         3
                Anti-Malware       0.00      0.00      0.00         3
                Art & Design       0.00      0.00      0.00         4
                  Blockchain       0.11      0.50      0.18         2
                       Books       0.67      0.67      0.67         3
                    Business       0.17      0.40      0.24         5
                    Calendar       0.60      1.00      0.75         3
Cloud Storage & File Sharing       1.00      0.33      0.50         3
              Cryptocurrency       0.64      0.58      0.61        12
           Currency Exchange       0.67      1.00      0.80         4
                 Development       0.56      0.22      0.31        23
    Documents & Productivity       0.38      0.60      0.46         5
                       Email       0.50      1.00      0.67         4
               Entertainment       0.25      0.50      0.33         2
                 Environment       1.00      1.00      1.00         3
                     Finance       0.33      0.30      0.32        10
                Food & Drink       0.67      0.50      0.57         4
              Games & Comics       0.41      0.44      0.42        16
                   Geocoding       0.75      0.64      0.69        14
                  Government       0.44      0.50      0.47        16
                      Health       0.00      0.00      0.00         6
                        Jobs       1.00      1.00      1.00         3
            Machine Learning       0.25      0.33      0.29         6
                       Music       1.00      0.80      0.89         5
                        News       0.60      0.75      0.67         4
                   Open Data       0.00      0.00      0.00         8
                       Other       0.57      0.31      0.40        13
                 Personality       0.60      0.75      0.67         4
                 Photography       0.17      0.25      0.20         4
              Science & Math       0.00      0.00      0.00         6
                    Security       0.38      0.43      0.40         7
                    Shopping       0.25      0.50      0.33         2
                      Social       0.43      0.38      0.40         8
            Sports & Fitness       0.60      0.86      0.71         7
                   Test Data       0.50      0.75      0.60         4
               Text Analysis       0.50      1.00      0.67         3
              Transportation       0.67      0.50      0.57        12
              URL Shorteners       0.43      1.00      0.60         3
                       Video       0.50      0.29      0.36         7
                     Weather       0.83      0.83      0.83         6

                    accuracy                           0.48       261
                   macro avg       0.49      0.55      0.49       261
                weighted avg       0.49      0.48      0.46       261

c:\Users\Hii\Code\ai-api-intelligence\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Hii\Code\ai-api-intelligence\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Hii\Code\ai-api-intelligence\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [35]:
print(train_df[train_df['category'] == 'Health']['description'].tolist())
print()
print(train_df[train_df['category'] == 'Anti-Malware']['description'].tolist())

['Humanitarian Data Exchange (HDX) is open platform for sharing data across crises and organisations', 'Oncology research, clinical trials, FDA approvals, news, and MAMMAL predictions', 'Vaccination data for Malaysia', 'API for Current cases and more stuff about COVID-19 and Influenza', 'Access to the data from the CMS - medicare.gov', 'Coronavirus API with free COVID-19 live updates', 'Public biological age competition data with biomarkers and rankings', 'Covid 19 cases, deaths and recovery per country', 'COVID-19 live statistics into sites per hour', 'Maps, datasets, applications and more in the context of COVID-19', 'Provides situation of the COVID-19 patients reported in Sri Lanka', 'Global and countrywise data of Covid 19 daily Summary, confirmed cases, recovered and deaths', 'HTTP API for Latest Covid-19 Data', 'Covid 19 statistics state and district wise about cases, vaccinations, recovery within India', 'Details on Covid-19 cases across Canada', 'Unofficial Covid-19 Web API for Philippines from data collected by DOH', 'Makeup Information', 'NLP that extracts mentions of clinical concepts from text, gives access to clinical ontology', 'Live Canadian emergency room closures and service disruptions, by province', 'Government measures tracker to fight against the Covid-19 pandemic', 'National Plan & Provider Enumeration System, info on healthcare providers registered in US', 'NLP based symptom checker and patient triage API for health diagnosis from text', 'Covid-19  data for the US', 'Genetic conditions, genes, chromosomes and mtDNA data', 'Food and nutrition data API with recipe search', 'Every clinical trial registered with ClinicalTrials.gov, indexed by condition and sponsor', 'Hourly emergency room occupancy, stretcher counts and wait times for every hospital in Quebec, Canada']

['Collect and share malware samples', 'Scan and Analyse URLs', 'Malware Archive / file sourcing', 'IP/domain/URL reputation', 'IP/domain/URL reputation', 'IP/domain/URL reputation', 'Community IP blacklist to check and report abusive IP addresses', 'VirusTotal File/URL Analysis', 'Provide malware datasets and threat intelligence feeds', 'Malware execution and analysis', 'Bulk queries and Download Malware Samples']

In [36]:
print(train_df['category'].value_counts()['Health'])
print(train_df['category'].value_counts()['Anti-Malware'])

27
11

In [37]:
for cat in ['Art & Design', 'Business', 'Finance']:
    print(f"=== {cat} (train count: {train_df['category'].value_counts().get(cat, 0)}) ===")
    print(train_df[train_df['category'] == cat]['description'].tolist())
    print()

=== Art & Design (train count: 17) ===
['Smithsonian Design Museum', 'Generate placeholder images with custom size, colors and text', 'Icons', 'AI image upscaling to 8K with 18 models (Real-ESRGAN, SeedVR2, AuraSR)', 'Art', 'Generate images for Discord users', 'SVG Icon Generator', 'Search and fetch SVG icons from 200+ open source icon sets', 'Discover the world’s top designers & creatives', 'Easily create word clouds', 'Art', 'European Museum and Galleries content', 'Favicons for any website, with fallbacks', 'Met Museum of Art', 'AI fashion design generator — transform Swedish text into clothing concepts', 'Curated architecture, design, photography and art projects with visual-similarity and taste metadata', 'RijksMuseum Data']

=== Business (train count: 22) ===
['Registered Domain Names Search', 'Generate PDF, JSON & UBL invoices in 11 languages from one JSON POST', 'Email Finder for B2B sales and email marketing and email verifier', 'Send marketing campaigns and transactional mails', 'Search for company logos and embed them in your projects', 'Get data for procurements in Romania in JSON format', 'Easy way to take payments, manage refunds, and help customers checkout online', 'Boards, lists and cards to help you organize and prioritize your projects', 'Trademark Search', 'Hire freelancers to get work done', 'Companies that just raised funding, scored as sales leads, from public SEC filings', 'Get data for procurements in Poland in JSON format', 'Search 47,000+ marketing agencies by service, location and rating', 'Person and company enrichment plus warm introduction paths through your network', 'Verified UK company profiles with an AI summary and accuracy score, from Companies House data', 'U.S. contractor datasets with a free discovery API for coverage, pricing and masked previews', 'Company lookup', 'GTM enrichment, lead generation, email verification, and company signals', 'Allows you to programmatically access and Smartsheet data and account information', 'Get data for procurements in Spain in JSON format', 'Access your queries and dashboards on Redash', 'Marketing email can be sent and mail templates made in MJML or HTML can be sent using API']

=== Finance (train count: 47) ===
['Validate VAT numbers and calculate VAT rates', 'Real-time AI-summarized SEC filings, Fed, FDA and BLS data, ticker-tagged', 'Cross-validated gold, silver & copper spot, futures & 30-year history in 13 currencies', 'All Banco do Brasil financial transaction APIs', 'Point-in-time quarterly revenue for 20 U.S. issuers', 'Instant VAT number and tax validation across the globe', 'Instant IBAN and SWIFT number validation across the globe', 'SEC filings, financial statements, earnings, ETF holdings and ownership data', 'Finage is a stock, currency, cryptocurrency, indices, and ETFs real-time & historical data provider', 'Connect to bank accounts using official bank APIs and get raw transaction data', 'Stock market data powered by SQL', 'Trading signals, market analysis and geopolitical intelligence', 'Resolve an IBAN to its bank name, BIC, city and address for 60+ countries', 'News with media bias scoring, balanced news synthesis, live market data, AI options pricing', 'Realtime and historical stock data', 'Daily AI-ranked stock and crypto watchlists', "Connect with user's bank accounts and access transaction data", 'Payment platform', 'The Moov API makes it simple for platforms to send, receive, and store money', 'WallstreetBets Stock Comments Sentiment Analysis', 'Clean SEC EDGAR company financials, ratios, filings and 10-K/10-Q sections as normalized JSON', 'Public access to a database of IIN/BIN information', 'Public-record bank and lender failure-risk evidence', 'A api to generate boletos in Brazil', 'Real-Time, Intraday & Historical Market Data API', 'Insider trading data, earnings call analysis, financial statements, and more', 'Spreadbetting and CFD Market Data', 'Real-Time RESTful APIs and Websocket for Stocks, Currencies, and Crypto', 'Realtime & Historical Stock and Market Data', 'Stock market data (real-time & historical)', 'Real-Time, Intraday & Historical Market Data, News and Sentiment API', 'Global macroeconomic data', 'Real-time and historical stock market data with 150+ exchanges', 'Realtime and historical stock data and current stock sentiment', 'Realtime and historical stock data', 'Equity, index, futures, options symbology from Bloomberg LP', 'Live economic data — CPI, PPI, energy, treasury rates, BTC premium', 'SEC EDGAR filings, XBRL financials, Form 4 insider trades, 8-K events and 13F holdings', 'Connect with users’ bank accounts and access transaction data in Africa', 'US Treasury auction results with the tail and bidder split, plus scored economic releases', 'Historical stock market data', 'Realtime and historical market data on all US equities and ETFs', 'API to access annual reports of public US companies', 'Shariah-compliant stock and ETF screening across 5 methodologies, zakat and purification', 'All Citigroup account and statement data APIs', 'Gain access to set of <SmartAPI> and create end-to-end broking services', 'Websocket API to access realtime stock data']

In [38]:
train_df['text_features'] = train_df['name'] + ' ' + train_df['description']
val_df['text_features'] = val_df['name'] + ' ' + val_df['description']
test_df['text_features'] = test_df['name'] + ' ' + test_df['description']

In [39]:
vectorizer2 = TfidfVectorizer(max_features=2000, stop_words='english')
X_train2 = vectorizer2.fit_transform(train_df['text_features'])
X_val2 = vectorizer2.transform(val_df['text_features'])

In [40]:
model2 = LogisticRegression(max_iter=1000, random_state=42, class_weight='balanced')
model2.fit(X_train2, train_df['category'])

LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)

In [41]:
val_predictions2 = model2.predict(X_val2)
accuracy2 = accuracy_score(val_df['category'], val_predictions2)

print(f"Validation accuracy (name+description): {accuracy2:.2%}")
print(classification_report(val_df['category'], val_predictions2))

Validation accuracy (name+description): 50.57%
                              precision    recall  f1-score   support

                     Animals       0.57      1.00      0.73         4
                       Anime       1.00      0.67      0.80         3
                Anti-Malware       0.00      0.00      0.00         3
                Art & Design       0.00      0.00      0.00         4
                  Blockchain       0.17      0.50      0.25         2
                       Books       0.50      0.67      0.57         3
                    Business       0.18      0.40      0.25         5
                    Calendar       1.00      1.00      1.00         3
Cloud Storage & File Sharing       1.00      0.33      0.50         3
              Cryptocurrency       0.73      0.67      0.70        12
           Currency Exchange       0.67      1.00      0.80         4
                 Development       0.46      0.26      0.33        23
    Documents & Productivity       1.00      0.60      0.75         5
                       Email       0.57      1.00      0.73         4
               Entertainment       0.40      1.00      0.57         2
                 Environment       1.00      1.00      1.00         3
                     Finance       0.23      0.30      0.26        10
                Food & Drink       0.67      0.50      0.57         4
              Games & Comics       0.50      0.31      0.38        16
                   Geocoding       0.77      0.71      0.74        14
                  Government       0.47      0.56      0.51        16
                      Health       1.00      0.33      0.50         6
                        Jobs       1.00      1.00      1.00         3
            Machine Learning       0.27      0.50      0.35         6
                       Music       0.83      1.00      0.91         5
                        News       0.50      0.75      0.60         4
                   Open Data       0.00      0.00      0.00         8
                       Other       0.75      0.46      0.57        13
                 Personality       0.40      0.50      0.44         4
                 Photography       0.20      0.25      0.22         4
              Science & Math       0.00      0.00      0.00         6
                    Security       0.22      0.29      0.25         7
                    Shopping       0.20      0.50      0.29         2
                      Social       0.60      0.38      0.46         8
            Sports & Fitness       0.67      0.86      0.75         7
                   Test Data       0.50      0.75      0.60         4
               Text Analysis       0.50      1.00      0.67         3
              Transportation       1.00      0.42      0.59        12
              URL Shorteners       0.43      1.00      0.60         3
                       Video       0.50      0.29      0.36         7
                     Weather       0.83      0.83      0.83         6

                    accuracy                           0.51       261
                   macro avg       0.54      0.58      0.52       261
                weighted avg       0.55      0.51      0.50       261

In [42]:
target_cats = ['Art & Design', 'Anti-Malware']
report_dict = classification_report(val_df['category'], val_predictions2, output_dict=True)

for cat in target_cats:
    print(cat, report_dict.get(cat, 'not in report'))

Art & Design {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 4.0}
Anti-Malware {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 3.0}

In [43]:
import joblib
joblib.dump(model2, '../artifacts/category_classifier.pkl')
joblib.dump(vectorizer2, '../artifacts/tfidf_vectorizer_v2.pkl')
print("Final model saved")

Final model saved

In [44]:
test_df['text_features'] = test_df['name'] + ' ' + test_df['description']
X_test2 = vectorizer2.transform(test_df['text_features'])

test_predictions = model2.predict(X_test2)
test_accuracy = accuracy_score(test_df['category'], test_predictions)

print(f"FINAL TEST accuracy: {test_accuracy:.2%}")
print(classification_report(test_df['category'], test_predictions))

FINAL TEST accuracy: 56.32%
                              precision    recall  f1-score   support

                     Animals       1.00      0.75      0.86         4
                       Anime       0.67      0.67      0.67         3
                Anti-Malware       0.50      0.50      0.50         2
                Art & Design       0.50      1.00      0.67         3
                  Blockchain       0.25      0.50      0.33         2
                       Books       0.67      0.50      0.57         4
                    Business       0.50      0.20      0.29         5
                    Calendar       1.00      1.00      1.00         2
Cloud Storage & File Sharing       0.40      1.00      0.57         2
              Cryptocurrency       0.90      0.75      0.82        12
           Currency Exchange       0.60      1.00      0.75         3
                 Development       0.43      0.25      0.32        24
    Documents & Productivity       0.33      0.50      0.40         6
                       Email       0.75      1.00      0.86         3
               Entertainment       0.22      0.67      0.33         3
                 Environment       0.67      0.50      0.57         4
                     Finance       0.55      0.60      0.57        10
                Food & Drink       0.75      0.75      0.75         4
              Games & Comics       0.47      0.53      0.50        15
                   Geocoding       0.73      0.73      0.73        15
                  Government       0.67      0.80      0.73        15
                      Health       1.00      0.33      0.50         6
                        Jobs       0.80      1.00      0.89         4
            Machine Learning       1.00      0.40      0.57         5
                       Music       0.83      0.83      0.83         6
                        News       0.25      0.33      0.29         3
                   Open Data       0.12      0.12      0.12         8
                       Other       0.43      0.23      0.30        13
                 Personality       0.50      0.75      0.60         4
                 Photography       0.30      0.60      0.40         5
              Science & Math       0.33      0.17      0.22         6
                    Security       0.33      0.14      0.20         7
                    Shopping       0.20      0.67      0.31         3
                      Social       1.00      0.57      0.73         7
            Sports & Fitness       0.75      0.86      0.80         7
                   Test Data       1.00      0.80      0.89         5
               Text Analysis       0.25      1.00      0.40         3
              Transportation       1.00      0.58      0.74        12
              URL Shorteners       0.75      1.00      0.86         3
                       Video       1.00      0.14      0.25         7
                     Weather       1.00      1.00      1.00         6

                    accuracy                           0.56       261
                   macro avg       0.62      0.63      0.58       261
                weighted avg       0.63      0.56      0.56       261

overfitting train accuracy >test

In [45]:
train_accuracy = model2.score(X_train2, train_df['category'])
print(f"Train accuracy: {train_accuracy:.2%}")
print(f"Test accuracy: {test_accuracy:.2%}")

Train accuracy: 88.15%
Test accuracy: 56.32%

In [46]:
model3 = LogisticRegression(max_iter=1000, random_state=42, class_weight='balanced', C=0.1)
model3.fit(X_train2, train_df['category'])

train_acc3 = model3.score(X_train2, train_df['category'])
val_acc3 = accuracy_score(val_df['category'], model3.predict(X_val2))

print(f"Train: {train_acc3:.2%}  Val: {val_acc3:.2%}")

Train: 79.09%  Val: 45.21%

In [47]:
model3 = LogisticRegression(max_iter=1000, random_state=42, class_weight='balanced', C=0.1)
model3.fit(X_train2, train_df['category'])

train_acc3 = model3.score(X_train2, train_df['category'])
val_acc3 = accuracy_score(val_df['category'], model3.predict(X_val2))

print(f"Train: {train_acc3:.2%}  Val: {val_acc3:.2%}")

Train: 79.09%  Val: 45.21%

In [48]:
model4 = LogisticRegression(max_iter=1000, random_state=42, class_weight='balanced', C=0.5)
model4.fit(X_train2, train_df['category'])

train_acc4 = model4.score(X_train2, train_df['category'])
val_acc4 = accuracy_score(val_df['category'], model4.predict(X_val2))

print(f"Train: {train_acc4:.2%}  Val: {val_acc4:.2%}")

Train: 84.28%  Val: 48.28%

In [49]:
vectorizer3 = TfidfVectorizer(max_features=500, stop_words='english')
X_train3 = vectorizer3.fit_transform(train_df['text_features'])
X_val3 = vectorizer3.transform(val_df['text_features'])

model5 = LogisticRegression(max_iter=1000, random_state=42, class_weight='balanced')
model5.fit(X_train3, train_df['category'])

train_acc5 = model5.score(X_train3, train_df['category'])
val_acc5 = accuracy_score(val_df['category'], model5.predict(X_val3))

print(f"Train: {train_acc5:.2%}  Val: {val_acc5:.2%}")

Train: 74.24%  Val: 47.13%

In [50]:
from sklearn.model_selection import cross_val_score

# Use train+val combined for CV, keep test untouched
cv_df = pd.concat([train_df, val_df])
cv_df['text_features'] = cv_df['name'] + ' ' + cv_df['description']

vectorizer_cv = TfidfVectorizer(max_features=2000, stop_words='english')
X_cv = vectorizer_cv.fit_transform(cv_df['text_features'])

model_cv = LogisticRegression(max_iter=1000, random_state=42, class_weight='balanced')
scores = cross_val_score(model_cv, X_cv, cv_df['category'], cv=5)

print(f"CV scores: {scores}")
print(f"Mean: {scores.mean():.2%}  Std: {scores.std():.2%}")

CV scores: [0.56418919 0.54237288 0.56271186 0.54576271 0.5220339 ]
Mean: 54.74%  Std: 1.54%

In [51]:
vectorizer_v3 = TfidfVectorizer(max_features=2000, stop_words='english', ngram_range=(1,2), min_df=2)
X_train_v3 = vectorizer_v3.fit_transform(train_df['text_features'])
X_val_v3 = vectorizer_v3.transform(val_df['text_features'])

model_v3 = LogisticRegression(max_iter=1000, random_state=42, class_weight='balanced')
model_v3.fit(X_train_v3, train_df['category'])

train_acc_v3 = model_v3.score(X_train_v3, train_df['category'])
val_acc_v3 = accuracy_score(val_df['category'], model_v3.predict(X_val_v3))

print(f"Train: {train_acc_v3:.2%}  Val: {val_acc_v3:.2%}")

Train: 83.05%  Val: 51.72%

In [52]:
vectorizer_v3 = TfidfVectorizer(
    max_features=2000, stop_words='english',
    ngram_range=(1,2), min_df=2
)

X_train_v3 = vectorizer_v3.fit_transform(train_df['text_features'])
X_val_v3 = vectorizer_v3.transform(val_df['text_features'])

In [53]:
model_v3 = LogisticRegression(
    max_iter=1000, random_state=42,
    class_weight='balanced'
)
model_v3.fit(X_train_v3, train_df['category'])

LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)

In [54]:
train_acc = model_v3.score(X_train_v3, train_df['category'])
val_acc = accuracy_score(
    val_df['category'], model_v3.predict(X_val_v3)
)

print(f"Train: {train_acc:.2%}")
print(f"Val: {val_acc:.2%}")

Train: 83.05%
Val: 51.72%

In [55]:
vectorizer_v4 = TfidfVectorizer(max_features=2000, stop_words='english', ngram_range=(1,1), sublinear_tf=True)
X_train_v4 = vectorizer_v4.fit_transform(train_df['text_features'])
X_val_v4 = vectorizer_v4.transform(val_df['text_features'])

model_v4 = LogisticRegression(max_iter=1000, random_state=42, class_weight='balanced')
model_v4.fit(X_train_v4, train_df['category'])

train_acc_v4 = model_v4.score(X_train_v4, train_df['category'])
val_acc_v4 = accuracy_score(val_df['category'], model_v4.predict(X_val_v4))

print(f"Train: {train_acc_v4:.2%}  Val: {val_acc_v4:.2%}")

Train: 88.40%  Val: 51.34%

In [56]:
from sklearn.svm import LinearSVC

model_svm = LinearSVC(class_weight='balanced', random_state=42, max_iter=1000)
model_svm.fit(X_train2, train_df['category'])

train_acc_svm = model_svm.score(X_train2, train_df['category'])
val_acc_svm = accuracy_score(val_df['category'], model_svm.predict(X_val2))

print(f"Train: {train_acc_svm:.2%}  Val: {val_acc_svm:.2%}")

Train: 99.34%  Val: 56.32%

In [57]:
model_svm2 = LinearSVC(class_weight='balanced', random_state=42, max_iter=1000, C=0.1)
model_svm2.fit(X_train2, train_df['category'])

train_acc_svm2 = model_svm2.score(X_train2, train_df['category'])
val_acc_svm2 = accuracy_score(val_df['category'], model_svm2.predict(X_val2))

print(f"Train: {train_acc_svm2:.2%}  Val: {val_acc_svm2:.2%}")

Train: 91.19%  Val: 50.57%

In [58]:
test_predictions_svm = model_svm.predict(X_test2)
test_acc_svm = accuracy_score(test_df['category'], test_predictions_svm)

print(f"SVM Test accuracy: {test_acc_svm:.2%}")

SVM Test accuracy: 61.69%

In [59]:
import joblib
joblib.dump(model_svm, '../artifacts/category_classifier_svm.pkl')
print("SVM model saved")

SVM model saved

In [60]:
from sentence_transformers import SentenceTransformer

embed_model = SentenceTransformer('all-MiniLM-L6-v2')

X_train_emb = embed_model.encode(train_df['text_features'].tolist())
X_val_emb = embed_model.encode(val_df['text_features'].tolist())
X_test_emb = embed_model.encode(test_df['text_features'].tolist())

print(X_train_emb.shape, X_val_emb.shape, X_test_emb.shape)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

(1215, 384) (261, 384) (261, 384)

In [61]:
model_emb = LogisticRegression(max_iter=1000, random_state=42, class_weight='balanced')
model_emb.fit(X_train_emb, train_df['category'])

train_acc_emb = model_emb.score(X_train_emb, train_df['category'])
val_acc_emb = accuracy_score(val_df['category'], model_emb.predict(X_val_emb))

print(f"Train: {train_acc_emb:.2%}  Val: {val_acc_emb:.2%}")

Train: 80.33%  Val: 60.54%

In [62]:
model_svm_emb = LinearSVC(class_weight='balanced', random_state=42, max_iter=1000)
model_svm_emb.fit(X_train_emb, train_df['category'])

train_acc_svm_emb = model_svm_emb.score(X_train_emb, train_df['category'])
val_acc_svm_emb = accuracy_score(val_df['category'], model_svm_emb.predict(X_val_emb))

print(f"Train: {train_acc_svm_emb:.2%}  Val: {val_acc_svm_emb:.2%}")

Train: 95.88%  Val: 62.84%

In [63]:
test_predictions_svm_emb = model_svm_emb.predict(X_test_emb)
test_acc_svm_emb = accuracy_score(test_df['category'], test_predictions_svm_emb)

print(f"SVM + Embeddings Test accuracy: {test_acc_svm_emb:.2%}")

SVM + Embeddings Test accuracy: 66.28%

In [64]:
import joblib

joblib.dump(model_svm_emb, '../artifacts/category_classifier_final.pkl')
embed_model.save('../artifacts/sentence_embedder')

print("Final model + embedder saved")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Final model + embedder saved

In [65]:
model_svm_emb2 = LinearSVC(class_weight='balanced', random_state=42, max_iter=1000, C=0.5)
model_svm_emb2.fit(X_train_emb, train_df['category'])

train_acc2 = model_svm_emb2.score(X_train_emb, train_df['category'])
val_acc2 = accuracy_score(val_df['category'], model_svm_emb2.predict(X_val_emb))

print(f"Train: {train_acc2:.2%}  Val: {val_acc2:.2%}")

Train: 92.76%  Val: 63.98%

In [66]:
test_predictions_svm_emb2 = model_svm_emb2.predict(X_test_emb)
test_acc_svm_emb2 = accuracy_score(test_df['category'], test_predictions_svm_emb2)

print(f"SVM(C=0.5) + Embeddings Test accuracy: {test_acc_svm_emb2:.2%}")

SVM(C=0.5) + Embeddings Test accuracy: 67.05%

In [67]:
embed_model2 = SentenceTransformer('all-mpnet-base-v2')

X_train_emb2 = embed_model2.encode(train_df['text_features'].tolist())
X_val_emb2 = embed_model2.encode(val_df['text_features'].tolist())
X_test_emb2 = embed_model2.encode(test_df['text_features'].tolist())

print(X_train_emb2.shape, X_val_emb2.shape, X_test_emb2.shape)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

(1215, 768) (261, 768) (261, 768)

In [68]:
model_svm_emb3 = LinearSVC(class_weight='balanced', random_state=42, max_iter=1000, C=0.5)
model_svm_emb3.fit(X_train_emb2, train_df['category'])

train_acc3 = model_svm_emb3.score(X_train_emb2, train_df['category'])
val_acc3 = accuracy_score(val_df['category'], model_svm_emb3.predict(X_val_emb2))

print(f"Train: {train_acc3:.2%}  Val: {val_acc3:.2%}")

Train: 93.58%  Val: 68.58%

In [69]:
test_predictions3 = model_svm_emb3.predict(X_test_emb2)
test_acc3 = accuracy_score(test_df['category'], test_predictions3)

print(f"SVM(C=0.5) + mpnet embeddings Test accuracy: {test_acc3:.2%}")

SVM(C=0.5) + mpnet embeddings Test accuracy: 67.82%

In [70]:
for c_val in [0.1, 0.3, 0.7, 1.0, 2.0]:
    m = LinearSVC(class_weight='balanced', random_state=42, max_iter=1000, C=c_val)
    m.fit(X_train_emb2, train_df['category'])
    val_acc = accuracy_score(val_df['category'], m.predict(X_val_emb2))
    print(f"C={c_val}: Val = {val_acc:.2%}")

C=0.1: Val = 65.52%
C=0.3: Val = 68.58%
C=0.7: Val = 68.20%
C=1.0: Val = 68.20%
C=2.0: Val = 67.82%

In [71]:
import numpy as np

def encode_metadata(df, auth_categories):
    auth_dummies = pd.get_dummies(df['auth'], prefix='auth')
    auth_dummies = auth_dummies.reindex(columns=auth_categories, fill_value=0)
    https_col = df['https'].astype(int)
    cors_col = df['cors'].map({True: 1, False: 0}).fillna(0.5)
    return pd.concat([https_col, cors_col, auth_dummies], axis=1).values

# Learn the full set of auth categories from TRAIN only (same rule as TF-IDF fit)
auth_categories = pd.get_dummies(train_df['auth'], prefix='auth').columns

meta_train = encode_metadata(train_df, auth_categories)
meta_val = encode_metadata(val_df, auth_categories)
meta_test = encode_metadata(test_df, auth_categories)

X_train_combined = np.hstack([X_train_emb2, meta_train])
X_val_combined = np.hstack([X_val_emb2, meta_val])
X_test_combined = np.hstack([X_test_emb2, meta_test])

print(X_train_combined.shape, X_val_combined.shape, X_test_combined.shape)

(1215, 775) (261, 775) (261, 775)

In [72]:
model_combined = LinearSVC(class_weight='balanced', random_state=42, max_iter=1000, C=0.5)
model_combined.fit(X_train_combined, train_df['category'])

train_acc_c = model_combined.score(X_train_combined, train_df['category'])
val_acc_c = accuracy_score(val_df['category'], model_combined.predict(X_val_combined))

print(f"Train: {train_acc_c:.2%}  Val: {val_acc_c:.2%}")

Train: 93.99%  Val: 68.20%

In [73]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
train_df['label'] = label_encoder.fit_transform(train_df['category'])
val_df['label'] = label_encoder.transform(val_df['category'])
test_df['label'] = label_encoder.transform(test_df['category'])

print(f"Number of classes: {len(label_encoder.classes_)}")

Number of classes: 41

In [74]:
print(train_df['category'].nunique())
print(sorted(train_df['category'].unique()))

41
['Animals', 'Anime', 'Anti-Malware', 'Art & Design', 'Blockchain', 'Books', 'Business', 'Calendar', 'Cloud Storage & File Sharing', 'Cryptocurrency', 'Currency Exchange', 'Development', 'Documents & Productivity', 'Email', 'Entertainment', 'Environment', 'Finance', 'Food & Drink', 'Games & Comics', 'Geocoding', 'Government', 'Health', 'Jobs', 'Machine Learning', 'Music', 'News', 'Open Data', 'Other', 'Personality', 'Photography', 'Science & Math', 'Security', 'Shopping', 'Social', 'Sports & Fitness', 'Test Data', 'Text Analysis', 'Transportation', 'URL Shorteners', 'Video', 'Weather']

In [75]:
from transformers import DistilBertTokenizer

tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')

def tokenize_texts(texts, max_length=128):
    return tokenizer(
        texts, padding='max_length', truncation=True,
        max_length=max_length, return_tensors='pt'
    )

train_encodings = tokenize_texts(train_df['text_features'].tolist())
val_encodings = tokenize_texts(val_df['text_features'].tolist())
test_encodings = tokenize_texts(test_df['text_features'].tolist())

print(train_encodings['input_ids'].shape)

torch.Size([1215, 128])

In [76]:
import torch

class APIDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        item = {key: val[idx] for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

train_dataset = APIDataset(train_encodings, train_df['label'].tolist())
val_dataset = APIDataset(val_encodings, val_df['label'].tolist())
test_dataset = APIDataset(test_encodings, test_df['label'].tolist())

print(len(train_dataset), len(val_dataset), len(test_dataset))

1215 261 261

In [78]:
import transformers
print(transformers.__version__)

5.16.1

In [80]:
training_args = TrainingArguments(
    output_dir='../artifacts/distilbert_checkpoints',
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    eval_strategy='epoch',
    save_strategy='epoch',
    load_best_model_at_end=True,
    metric_for_best_model='eval_loss',
    logging_steps=10,
)

In [83]:
def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = predictions.argmax(axis=-1)
    return {'accuracy': accuracy_score(labels, predictions)}

trainer = Trainer(
    model=model_bert,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics,
)

trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

c:\Users\Hii\Code\ai-api-intelligence\.venv\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

c:\Users\Hii\Code\ai-api-intelligence\.venv\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=228, training_loss=2.1767605522222686, metrics={'train_runtime': 2610.0026, 'train_samples_per_second': 1.397, 'train_steps_per_second': 0.087, 'total_flos': 120794872631040.0, 'train_loss': 2.1767605522222686, 'epoch': 3.0})

In [86]:
print(model_svm_emb3.predict(X_val_emb2[:3]))

['Other' 'Development' 'Photography']

In [87]:
from sklearn.metrics import confusion_matrix, top_k_accuracy_score

# Top-3 accuracy needs decision_function scores, not just predictions
decision_scores = model_svm_emb3.decision_function(X_test_emb2)
top3_acc = top_k_accuracy_score(test_df['category'], decision_scores, k=3, labels=model_svm_emb3.classes_)
print(f"Top-3 test accuracy: {top3_acc:.2%}")

Top-3 test accuracy: 84.67%

In [88]:
print(model_svm_emb3.predict(X_val_emb2[:3]))

['Other' 'Development' 'Photography']

In [89]:
from sklearn.metrics import top_k_accuracy_score

decision_scores = model_svm_emb3.decision_function(X_test_emb2)
top3_acc = top_k_accuracy_score(test_df['category'], decision_scores, k=3, labels=model_svm_emb3.classes_)
print(f"Top-3 test accuracy: {top3_acc:.2%}")

Top-3 test accuracy: 84.67%

In [90]:
from sklearn.metrics import confusion_matrix
import pandas as pd

cm = confusion_matrix(test_df['category'], test_predictions3, labels=model_svm_emb3.classes_)
cm_df = pd.DataFrame(cm, index=model_svm_emb3.classes_, columns=model_svm_emb3.classes_)

# Find the biggest mix-ups: pairs where the model confused one category for another
confusions = []
for true_cat in cm_df.index:
    for pred_cat in cm_df.columns:
        if true_cat != pred_cat and cm_df.loc[true_cat, pred_cat] > 0:
            confusions.append((true_cat, pred_cat, cm_df.loc[true_cat, pred_cat]))

confusions_df = pd.DataFrame(confusions, columns=['True', 'Predicted_As', 'Count']).sort_values('Count', ascending=False)
print(confusions_df.head(15))

                True    Predicted_As  Count
42         Open Data      Government      3
39  Machine Learning   Text Analysis      2
41         Open Data     Environment      2
53       Photography    Art & Design      2
38            Health    Food & Drink      2
14       Development       Geocoding      2
37        Government        Business      2
11       Development      Blockchain      2
49             Other       Geocoding      2
70             Video  Games & Comics      2
8           Business   Text Analysis      1
6           Business      Government      1
5           Business         Finance      1
4           Business           Email      1
3              Books   Entertainment      1

In [91]:
print(test_df[(test_df['category'] == 'Development') & (test_predictions3 == 'Blockchain')]['description'].tolist())

['Query information about your favorite Node.js libraries programatically', "Google's mobile application development platform that helps build, improve, and grow app"]